import React, { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Modal, Alert } from 'react-native';
// Using simple emoji for trash icon to avoid adding native icon deps
import { colors } from '../../theme/colors';
import { PathPlanWaypoint } from '../../types/pathplan';
import { ModeSelectionDialog } from './ModeSelectionDialog';
import { DashConfigDialog } from './DashConfigDialog';
import { useRover } from '../../context/RoverContext';
import { setMissionMode as setBackendMissionMode } from '../../services/missionModeService';

type Props = {
    waypoints: PathPlanWaypoint[];
    /** optional rover position supplied by the parent screen */
    roverPosition?: { lat: number; lon: number; alt?: number } | null;
    onUpdateWaypoints?: (waypoints: PathPlanWaypoint[]) => void;
    onLoadMission?: () => void;
    isFullScreen?: boolean;
    onToggleFullScreen?: () => void;
    isDeleteMode?: boolean;
    selectedForDelete?: number[];
    onToggleDeleteMode?: () => void;
    onToggleSelectAll?: () => void;
    onBulkDelete?: () => void;
    /**
     * Called when the component generates an export. Mobile hosts should save/share the content.
     * signature: (format, content, filename)
     */
    onExportMission?: (format: string, content: string, filename?: string) => void;
    /**
     * Called to request upload (host should open a native file picker and then call onUpdateWaypoints)
     */
    onRequestUpload?: () => void;
    /**
     * Called when user selects Manual Control mode to open fullscreen control UI
     */
    onManualControlOpen?: () => void;
};

const MissionOpsPanel: React.FC<Props> = ({
    waypoints,
    roverPosition = null,
    onUpdateWaypoints,
    onLoadMission,
    isFullScreen,
    onToggleFullScreen,
    isDeleteMode = false,
    selectedForDelete = [],
    onToggleDeleteMode = () => { },
    onToggleSelectAll = () => { },
    onBulkDelete = () => { },
    onExportMission,
    onRequestUpload,
    onManualControlOpen,
}) => {
    const { missionMode, setMissionMode } = useRover();
    const [showExportDialog, setShowExportDialog] = useState(false);
    const [selectedExportFormat, setSelectedExportFormat] = useState<'qgc' | 'json' | 'kml' | 'csv' | 'dxf'>('qgc');
    const [showModeDialog, setShowModeDialog] = useState(false);

    // Dash mode configuration
    const [dashDistance, setDashDistance] = useState(5.0);
    const [dashGap, setDashGap] = useState(3.0);
    const [showDashConfigDialog, setShowDashConfigDialog] = useState(false);

    // Check if manual control mode is active
    const isManualControlMode = missionMode === 'Manual Control';

    // Export generators (adapted for PathPlanWaypoint: uses `lon` field)
    const toQGCWPL110 = (wps: PathPlanWaypoint[]): string => {
        let fileContent = 'QGC WPL 110\n';
        if (wps.length > 0) {
            const homeLat = Number(wps[0].lat).toFixed(7);
            const homeLon = Number(wps[0].lon).toFixed(7);
            fileContent += `0\t1\t0\t16\t0\t0\t0\t0\t${homeLat}\t${homeLon}\t0\t1\n`;
        }

        wps.forEach((wp, index) => {
            const frame = 3;
            const commandId = 16; // default WAYPOINT
            const current = index === 0 ? 1 : 0;
            const autocont = 1;

            const line = [
                index + 1,
                current,
                frame,
                commandId,
                0,
                0,
                0,
                0,
                Number(wp.lat).toFixed(7),
                Number(wp.lon).toFixed(7),
                wp.alt,
                autocont,
            ].join('\t');

            fileContent += line + '\n';
        });

        return fileContent;
    };

    const generateKML = (wps: PathPlanWaypoint[]) => {
        const header = `<?xml version="1.0" encoding="UTF-8"?>\n<kml xmlns="http://www.opengis.net/kml/2.2">\n  <Document>\n    <name>Mission Waypoints</name>\n    <description>Generated by App</description>`;
        const placemarks = wps
            .map((wp, idx) => `\n    <Placemark>\n      <name>WP ${idx + 1}</name>\n      <description>Altitude: ${wp.alt}m</description>\n      <Point>\n        <coordinates>${wp.lon},${wp.lat},${wp.alt}</coordinates>\n      </Point>\n    </Placemark>`)
            .join('');
        const footer = `\n  </Document>\n</kml>`;
        return header + placemarks + footer;
    };

    const generateCSV = (wps: PathPlanWaypoint[]) => {
        const headers = ['Index', 'Latitude', 'Longitude', 'Altitude'];
        const rows = wps.map((wp, idx) => [idx + 1, wp.lat.toFixed(7), wp.lon.toFixed(7), wp.alt.toFixed(2)]);
        return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
    };

    const generateDXF = (wps: PathPlanWaypoint[]) => {
        const header = `  0\nSECTION\n  2\nHEADER\n  9\n$ACADVER\n  1\nAC1015\n  9\n$INSUNITS\n  70\n6\n  0\nENDSEC\n  0\nSECTION\n  2\nTABLES\n`;
        const points = wps
            .map((wp) => {
                const x = wp.lon * 111320;
                const y = wp.lat * 110540;
                const z = wp.alt;
                return `  0\nPOINT\n  8\nWAYPOINTS\n  10\n${x.toFixed(3)}\n  20\n${y.toFixed(3)}\n  30\n${z.toFixed(3)}\n  62\n1\n`;
            })
            .join('');
        const footer = `  0\nENDSEC\n  0\nEOF\n`;
        return header + points + footer;
    };

    const handleUpload = () => {
        // Host should open native picker and call onUpdateWaypoints after parsing
        try {
            console.log('[MissionOpsPanel] Upload button pressed, calling onRequestUpload');
        } catch (e) { }
        onRequestUpload?.();
    };

    const handleExportClick = () => {
        if (waypoints.length === 0) {
            Alert.alert('No mission to export.');
            return;
        }
        setShowExportDialog(true);
    };

    const confirmExport = (format: typeof selectedExportFormat) => {
        setShowExportDialog(false);
        let content = '';
        let filename = 'mission.txt';
        switch (format) {
            case 'qgc':
                content = toQGCWPL110(waypoints);
                filename = 'mission.waypoints';
                break;
            case 'json':
                content = JSON.stringify(waypoints, null, 2);
                filename = 'mission.json';
                break;
            case 'csv':
                content = generateCSV(waypoints);
                filename = 'mission.csv';
                break;
            case 'kml':
                content = generateKML(waypoints);
                filename = 'mission.kml';
                break;
            case 'dxf':
                content = generateDXF(waypoints);
                filename = 'mission.dxf';
                break;
        }

        if (onExportMission) {
            onExportMission(format, content, filename);
        } else {
            // Fallback: log to console if handler not provided
            console.log('[MissionOpsPanel] Export handler not provided');
            console.log('Export content sample:\n', content.slice(0, 500));
            Alert.alert('Export Ready', `Mission data (${format.toUpperCase()}) generated but export handler not configured.`);
        }
    };

    const handleLoadMission = async () => {
        console.log('[MissionOpsPanel] 🚀 Load Mission button clicked');
        console.log('[MissionOpsPanel] Waypoints count:', waypoints.length);
        console.log('[MissionOpsPanel] Current mission mode:', missionMode);
        
        if (waypoints.length === 0) {
            console.log('[MissionOpsPanel] ❌ No waypoints to load');
            Alert.alert('No Data', 'No marking points to load');
            return;
        }

        // Map frontend mode to backend mode
        let backendMode: 'auto' | 'continuous' | 'dash' = 'auto';
        let modeConfig = {};

        if (missionMode === 'Continuous') {
            backendMode = 'continuous';
        } else if (missionMode === 'Dash') {
            backendMode = 'dash';
            modeConfig = {
                dash_servo_on_time: dashDistance,
                dash_servo_off_time: dashGap,
            };
        }

        console.log('[MissionOpsPanel] Backend mode:', backendMode);
        console.log('[MissionOpsPanel] Mode config:', modeConfig);

        // First, set the mission mode on backend
        try {
            console.log('[MissionOpsPanel] 📡 Setting mission mode on backend...');
            const modeResult = await setBackendMissionMode({ mode: backendMode, ...modeConfig });
            console.log('[MissionOpsPanel] Mode result:', modeResult);
            
            if (!modeResult.success) {
                console.log('[MissionOpsPanel] ⚠️ Failed to set mission mode:', modeResult.error);
                // Continue anyway - the mode might be set later
            } else {
                console.log('[MissionOpsPanel] ✅ Mission mode set to:', backendMode, modeConfig);
            }
        } catch (error) {
            console.log('[MissionOpsPanel] ❌ Error setting mission mode:', error);
            console.log('[MissionOpsPanel] Error details:', {
                message: (error as any)?.message,
                code: (error as any)?.code,
                stack: (error as any)?.stack,
            });
            // Continue anyway
        }

        // Then load the mission
        console.log('[MissionOpsPanel] 📋 Showing confirmation alert...');
        Alert.alert('Load Mission', `Load mission with ${waypoints.length} marking points in ${missionMode} mode?`, [
            { text: 'Cancel', style: 'cancel', onPress: () => console.log('[MissionOpsPanel] User cancelled load') },
            { 
                text: 'Load', 
                onPress: () => {
                    console.log('[MissionOpsPanel] ✅ User confirmed load, calling onLoadMission...');
                    onLoadMission?.();
                }
            },
        ]);
    };

    const lastWaypoint = waypoints.length ? waypoints[waypoints.length - 1] : null;

    // Handle exit from manual control mode
    const handleExitManualMode = () => {
        setMissionMode('DGPS Mark');
    };

    const handleModeSelect = async (mode: string) => {
        setMissionMode(mode);
        setShowModeDialog(false);

        // If Dash mode selected, show the Dash config dialog (API called after config)
        if (mode === 'Dash') {
            setShowDashConfigDialog(true);
            return;
        }

        // Call backend API immediately for other modes
        let backendMode: 'auto' | 'continuous' | 'dash' = 'auto';
        if (mode === 'Continuous') {
            backendMode = 'continuous';
        }

        try {
            const result = await setBackendMissionMode({ mode: backendMode });
            if (result.success) {
                console.log('[MissionOpsPanel] Mode set successfully:', backendMode);
            } else {
                console.error('[MissionOpsPanel] Failed to set mode:', result.error);
            }
        } catch (error) {
            console.error('[MissionOpsPanel] Error calling setMissionMode:', error);
        }

        // If manual control selected, open the manual control UI
        if (mode === 'Manual Control') {
            onManualControlOpen?.();
        }
    };

    const handleDashConfigConfirm = async (onTime: number, offTime: number) => {
        setDashDistance(onTime);
        setDashGap(offTime);
        setShowDashConfigDialog(false);
        console.log('[MissionOpsPanel] Dash config set:', { onTime, offTime });

        // Call backend API with dash configuration
        try {
            const result = await setBackendMissionMode({
                mode: 'dash',
                dash_servo_on_time: onTime,
                dash_servo_off_time: offTime,
            });
            if (result.success) {
                console.log('[MissionOpsPanel] Dash mode set successfully');
            } else {
                console.error('[MissionOpsPanel] Failed to set dash mode:', result.error);
            }
        } catch (error) {
            console.error('[MissionOpsPanel] Error calling setMissionMode for dash:', error);
        }
    };

    const handleDashConfigCancel = () => {
        // Revert to DGPS Mark mode if user cancels Dash config
        setMissionMode('DGPS Mark');
        setShowDashConfigDialog(false);
    };

    return (
        <View style={styles.container}>
            <View style={styles.headerCard}>
                <Text style={styles.title}>MISSION OPS</Text>
            </View>

            {/* Mode Selection Card */}
            <View style={styles.modeCardTop}>
                <View style={styles.modeDisplay}>
                    <View style={styles.modeInfo}>
                        <Text style={styles.modeLabel}>Current Mode:</Text>
                        <Text style={styles.modeValue}>{missionMode}</Text>
                    </View>
                    <TouchableOpacity
                        style={styles.setModeButton}
                        onPress={() => setShowModeDialog(true)}
                        activeOpacity={0.7}
                    >
                        <Text style={styles.setModeButtonText}>⚙️ Set Mode</Text>
                    </TouchableOpacity>
                </View>
            </View>

            {/* Mode Selection Dialog */}
            <ModeSelectionDialog
                visible={showModeDialog}
                currentMode={missionMode}
                onSelectMode={handleModeSelect}
                onCancel={() => setShowModeDialog(false)}
            />

            {/* Dash Mode Config Dialog */}
            <DashConfigDialog
                visible={showDashConfigDialog}
                initialDistance={dashDistance}
                initialGap={dashGap}
                onConfirm={handleDashConfigConfirm}
                onCancel={handleDashConfigCancel}
            />

            {/* Conditionally render Manual Control placeholder or standard mission controls */}
            {isManualControlMode ? (
                <View style={styles.manualPlaceholder}>
                    <Text style={styles.manualTitle}>Manual Control</Text>
                    <Text style={styles.manualSubtitle}>Opens in fullscreen for safer operation.</Text>
                    <TouchableOpacity style={styles.manualOpenBtn} onPress={onManualControlOpen}>
                        <Text style={styles.manualOpenText}>Open Manual Control</Text>
                    </TouchableOpacity>
                    <TouchableOpacity style={styles.manualExitBtn} onPress={handleExitManualMode}>
                        <Text style={styles.manualExitText}>← Back to Mission Modes</Text>
                    </TouchableOpacity>
                </View>
            ) : (
                <>
                    <View style={styles.buttonsRow}>
                        <TouchableOpacity style={[styles.button, styles.uploadBtn]} onPress={handleUpload}>
                            <Text style={styles.buttonText}>📤 Upload</Text>
                        </TouchableOpacity>
                        <TouchableOpacity
                            style={[styles.button, waypoints.length ? styles.exportBtn : styles.disabledBtn]}
                            onPress={handleExportClick}
                        >
                            <Text style={styles.buttonText}>⬇️ Export</Text>
                        </TouchableOpacity>
                    </View>

                    <TouchableOpacity
                        style={[styles.loadButton, waypoints.length ? styles.loadActive : styles.disabledBtn]}
                        onPress={handleLoadMission}
                    >
                        <Text style={styles.loadText}>🚀 Load Mission</Text>
                    </TouchableOpacity>

                    <View style={styles.footerRow}>
                        {isDeleteMode ? (
                            <>
                                <TouchableOpacity onPress={onToggleSelectAll}>
                                    <Text style={styles.selectAllText}>{selectedForDelete.length === waypoints.length ? 'Deselect All' : 'Select All'}</Text>
                                </TouchableOpacity>
                                <View style={styles.deleteControls}>
                                    <Text style={styles.selectedCount}>{selectedForDelete.length} selected</Text>
                                    <TouchableOpacity style={styles.deleteBtn} onPress={onBulkDelete} disabled={selectedForDelete.length === 0}>
                                        <Text style={styles.deleteBtnText}>Delete</Text>
                                    </TouchableOpacity>
                                    <TouchableOpacity style={styles.cancelBtn} onPress={onToggleDeleteMode}>
                                        <Text style={styles.cancelBtnText}>Cancel</Text>
                                    </TouchableOpacity>
                                </View>
                            </>
                        ) : (
                            <>
                                <View>
                                    <Text style={styles.coordsText}>X:{lastWaypoint ? lastWaypoint.lat.toFixed(7) : ''} Y:{lastWaypoint ? (lastWaypoint as any).lon.toFixed(7) : ''}</Text>
                                </View>
                                <TouchableOpacity
                                    style={styles.trashIcon}
                                    onPress={() => {
                                        if (waypoints.length === 0) return;
                                        if (onUpdateWaypoints) {
                                            // Show confirmation alert
                                            Alert.alert(
                                                'Delete All Marking Points',
                                                `Are you sure you want to delete all ${waypoints.length} marking points? This action cannot be undone.`,
                                                [
                                                    {
                                                        text: 'Cancel',
                                                        style: 'cancel'
                                                    },
                                                    {
                                                        text: 'Delete All',
                                                        style: 'destructive',
                                                        onPress: () => onUpdateWaypoints([])
                                                    }
                                                ]
                                            );
                                        }
                                    }}
                                    disabled={waypoints.length === 0}
                                >
                                    <Text style={{ color: waypoints.length === 0 ? '#555' : colors.accent, fontSize: 18 }}>🗑️</Text>
                                </TouchableOpacity>
                            </>
                        )}
                    </View>
                </>
            )}

            {/* Export modal */}
            <Modal visible={showExportDialog} transparent animationType="fade" onRequestClose={() => setShowExportDialog(false)}>
                <View style={styles.modalOverlay}>
                    <View style={styles.modalContent}>
                        <Text style={styles.modalTitle}>Select Export Format</Text>

                        <TouchableOpacity style={styles.formatBtn} onPress={() => confirmExport('qgc')}>
                            <Text style={styles.formatText}>QGC Marking Points (.waypoints)</Text>
                        </TouchableOpacity>
                        <TouchableOpacity style={styles.formatBtn} onPress={() => confirmExport('json')}>
                            <Text style={styles.formatText}>JSON (.json)</Text>
                        </TouchableOpacity>
                        <TouchableOpacity style={styles.formatBtn} onPress={() => confirmExport('csv')}>
                            <Text style={styles.formatText}>CSV (.csv)</Text>
                        </TouchableOpacity>
                        <TouchableOpacity style={styles.formatBtn} onPress={() => confirmExport('kml')}>
                            <Text style={styles.formatText}>KML (.kml)</Text>
                        </TouchableOpacity>
                        <TouchableOpacity style={styles.formatBtn} onPress={() => confirmExport('dxf')}>
                            <Text style={styles.formatText}>DXF (.dxf)</Text>
                        </TouchableOpacity>

                        <TouchableOpacity style={[styles.formatBtn, styles.cancelBtn]} onPress={() => setShowExportDialog(false)}>
                            <Text style={styles.cancelBtnText}>Cancel</Text>
                        </TouchableOpacity>
                    </View>
                </View>
            </Modal>
        </View>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.panelBg,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 12,
        gap: 12,
    },
    headerCard: {
        alignItems: 'center',
        paddingVertical: 6,
    },
    title: {
        color: colors.accent,
        fontSize: 13,
        fontWeight: '700',
        letterSpacing: 1,
    },
    buttonsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 8,
    },
    button: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 4,
    },
    uploadBtn: {
        backgroundColor: colors.greenBtn,
    },
    exportBtn: {
        backgroundColor: colors.blueBtn,
    },
    disabledBtn: {
        backgroundColor: '#475569',
    },
    buttonText: {
        color: colors.text,
        fontWeight: '600',
    },
    loadButton: {
        marginTop: 8,
        borderRadius: 10,
        paddingVertical: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    loadActive: {
        backgroundColor: '#7c3aed',
    },
    loadText: {
        color: colors.text,
        fontWeight: '700',
    },
    footerRow: {
        marginTop: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    coordsText: {
        color: colors.textSecondary,
        fontFamily: 'monospace',
        fontSize: 12,
    },
    trashIcon: {
        padding: 6,
    },
    selectAllText: {
        color: colors.accent,
        fontSize: 12,
    },
    deleteControls: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    selectedCount: {
        color: colors.textSecondary,
        fontSize: 12,
    },
    deleteBtn: {
        backgroundColor: '#dc2626',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 6,
    },
    deleteBtnText: { color: 'white', fontWeight: '700' },
    cancelBtn: {
        backgroundColor: colors.inputBg,
        paddingHorizontal: 8,
        paddingVertical: 6,
        borderRadius: 6,
    },
    cancelBtnText: { color: colors.text, fontWeight: '700' },
    modeCard: {
        marginTop: 10,
        backgroundColor: 'rgba(2,6,23,0.2)',
        borderRadius: 10,
        padding: 10,
    },
    modeTitle: {
        color: colors.accent,
        fontWeight: '700',
        marginBottom: 6,
    },
    pickerWrap: {
        backgroundColor: colors.inputBg,
        borderRadius: 8,
        overflow: 'hidden',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContent: {
        backgroundColor: colors.panelBg,
        borderRadius: 12,
        padding: 20,
        width: '100%',
        maxWidth: 400,
        borderWidth: 1,
        borderColor: colors.border,
    },
    modalTitle: {
        color: colors.text,
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 12,
        textAlign: 'center',
    },
    formatBtn: {
        backgroundColor: '#003366',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: 'rgba(34,211,238,0.3)',
        alignItems: 'center',
    },
    formatText: {
        color: colors.text,
        fontWeight: '600',
    },
    modeCardTop: {
        height: '18%',
        marginBottom: 6,
        justifyContent: 'center',
    },
    modeDisplay: {
        height: '100%',
        borderRadius: 8,
        backgroundColor: colors.cardBg,
        borderWidth: 1,
        borderColor: colors.border,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 12,
    },
    modeInfo: {
        flex: 1,
    },
    modeLabel: {
        fontSize: 11,
        color: colors.textSecondary,
        marginBottom: 4,
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    modeValue: {
        fontSize: 16,
        color: colors.primary,
        fontWeight: '700',
    },
    setModeButton: {
        backgroundColor: colors.blueBtn,
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(103, 232, 249, 0.35)',
    },
    setModeButtonText: {
        color: colors.text,
        fontWeight: '700',
        fontSize: 13,
    },
    pickerWrapTop: {
        height: '100%',
        borderRadius: 8,
        overflow: 'hidden',
        backgroundColor: colors.inputBg,
    },
    manualPlaceholder: {
        backgroundColor: 'rgba(6, 182, 212, 0.06)',
        borderRadius: 10,
        padding: 14,
        borderWidth: 1,
        borderColor: 'rgba(6, 182, 212, 0.25)',
        gap: 10,
    },
    manualTitle: {
        color: colors.accent,
        fontWeight: '800',
        fontSize: 14,
        letterSpacing: 0.5,
    },
    manualSubtitle: {
        color: colors.textSecondary,
        fontSize: 12,
    },
    manualOpenBtn: {
        backgroundColor: colors.blueBtn,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(103, 232, 249, 0.35)',
    },
    manualOpenText: {
        color: colors.text,
        fontWeight: '700',
        fontSize: 13,
    },
    manualExitBtn: {
        backgroundColor: colors.inputBg,
        paddingVertical: 10,
        borderRadius: 8,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
    },
    manualExitText: {
        color: colors.text,
        fontWeight: '600',
        fontSize: 12,
    },
});

export default MissionOpsPanel;
